#!/usr/bin/env bash
#
# Turns a directory of .mobileprovision files into everything xcodebuild needs
# to produce a signed .ipa: per-target xcconfig files and an ExportOptions.plist.
#
# Profiles are matched to targets by the bundle identifier inside each profile,
# so the order they arrive in does not matter and renaming the bundle IDs in
# project.yml does not break anything.
#
#   usage: configure-signing.sh <profile-dir> <team-id> <export-method> <out-plist>
#
# Runs on macOS: it needs `security` and PlistBuddy to read the profiles.

set -euo pipefail

PROFILE_DIR="${1:?profile directory required}"
TEAM_ID="${2:?team id required}"
EXPORT_METHOD="${3:?export method required}"
OUT_PLIST="${4:?output plist path required}"

IOS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SIGNING_DIR="$IOS_DIR/Signing"
PLIST_BUDDY=/usr/libexec/PlistBuddy

# Xcode has moved this directory over the years; install into both so the
# profile is found regardless of version.
PROFILE_INSTALL_DIRS=(
  "$HOME/Library/MobileDevice/Provisioning Profiles"
  "$HOME/Library/Developer/Xcode/UserData/Provisioning Profiles"
)
for dir in "${PROFILE_INSTALL_DIRS[@]}"; do mkdir -p "$dir"; done

# bundle id -> profile name, accumulated as we read each profile.
declare -a MAPPED_BUNDLES=()
declare -a MAPPED_NAMES=()

shopt -s nullglob
profiles=("$PROFILE_DIR"/*.mobileprovision)
if [ ${#profiles[@]} -eq 0 ]; then
  echo "error: no .mobileprovision files in $PROFILE_DIR" >&2
  exit 1
fi

echo "Reading ${#profiles[@]} provisioning profile(s)"

for profile in "${profiles[@]}"; do
  decoded="$(mktemp)"
  security cms -D -i "$profile" > "$decoded"

  name="$($PLIST_BUDDY -c 'Print :Name' "$decoded")"
  uuid="$($PLIST_BUDDY -c 'Print :UUID' "$decoded")"
  app_id="$($PLIST_BUDDY -c 'Print :Entitlements:application-identifier' "$decoded")"
  bundle_id="${app_id#*.}"   # strip the leading TEAMID.

  if [[ "$bundle_id" == *"*"* ]]; then
    echo "error: '$name' is a wildcard profile. Family Controls needs an" >&2
    echo "       explicit App ID per target, so each profile must name one" >&2
    echo "       exact bundle identifier." >&2
    exit 1
  fi

  for dir in "${PROFILE_INSTALL_DIRS[@]}"; do
    cp "$profile" "$dir/$uuid.mobileprovision"
  done

  MAPPED_BUNDLES+=("$bundle_id")
  MAPPED_NAMES+=("$name")
  echo "  $bundle_id -> $name ($uuid)"
  rm -f "$decoded"
done

lookup_profile_name() {
  local want="$1" i
  for i in "${!MAPPED_BUNDLES[@]}"; do
    if [ "${MAPPED_BUNDLES[$i]}" = "$want" ]; then
      printf '%s' "${MAPPED_NAMES[$i]}"
      return 0
    fi
  done
  return 1
}

# Target -> bundle id, read straight out of project.yml so the two can never
# drift apart.
targets_and_bundles="$(python3 - "$IOS_DIR/project.yml" <<'PY'
import re, sys

spec = open(sys.argv[1]).read()
targets = spec.split("\ntargets:", 1)[1]
# Two-space indented keys are target names; PRODUCT_BUNDLE_IDENTIFIER lives
# in the settings block beneath each.
current = None
for line in targets.splitlines():
    target = re.match(r"^  ([A-Za-z][A-Za-z0-9_]*):\s*$", line)
    if target:
        current = target.group(1)
    bundle = re.search(r"PRODUCT_BUNDLE_IDENTIFIER:\s*(\S+)", line)
    if bundle and current:
        print(f"{current}\t{bundle.group(1)}")
        current = None
PY
)"

if [ -z "$targets_and_bundles" ]; then
  echo "error: could not read any targets out of project.yml" >&2
  exit 1
fi

# ExportOptions.plist, built up as we go.
rm -f "$OUT_PLIST"
$PLIST_BUDDY -c "Add :method string $EXPORT_METHOD" \
             -c "Add :teamID string $TEAM_ID" \
             -c "Add :signingStyle string manual" \
             -c "Add :stripSwiftSymbols bool true" \
             -c "Add :compileBitcode bool false" \
             -c "Add :provisioningProfiles dict" \
             "$OUT_PLIST" > /dev/null

missing=0
while IFS=$'\t' read -r target bundle_id; do
  [ -n "$target" ] || continue

  if ! profile_name="$(lookup_profile_name "$bundle_id")"; then
    echo "error: no provisioning profile supplied for $target ($bundle_id)" >&2
    missing=1
    continue
  fi

  cat > "$SIGNING_DIR/$target.xcconfig" <<EOF
// Generated by configure-signing.sh during the release build. Not the version
// committed to the repository; see that file for what the defaults are.
CODE_SIGN_STYLE = Manual
DEVELOPMENT_TEAM = $TEAM_ID
PROVISIONING_PROFILE_SPECIFIER = $profile_name
CODE_SIGN_IDENTITY = Apple Distribution
EOF

  $PLIST_BUDDY -c "Add :provisioningProfiles:$bundle_id string $profile_name" \
               "$OUT_PLIST" > /dev/null
  echo "  configured $target"
done <<< "$targets_and_bundles"

if [ "$missing" -ne 0 ]; then
  echo "" >&2
  echo "Every target needs its own profile. Profiles provided covered:" >&2
  printf '  %s\n' "${MAPPED_BUNDLES[@]}" >&2
  exit 1
fi

echo "Wrote $OUT_PLIST"
